### ISSUE TITLE
Can u make it for Coin-M?

### ISSUE THREAD

**Issue by MBillar** [frathon/hedgehog#4]
Subject:)

**Comment by Cinderella-Man** [comment]
Hi @MBillar :wave: 

Thank you very much for opening the issue :+1: 

I need to admit that I never used any leveraged products from Binance, but I think I would be personally interested in getting my head around those at some moment :sunglasses: 

Just for reference for people not aware of what Coin-M is => [Coin-Margined Futures Contracts](https://www.binance.com/en/support/articles/a4470430e3164c13932be8967961aede)
Another article from Binance: [Three Benefits of COIN-margined Perpetual Futures That You Need To Know](https://www.binance.com/en/blog/421499824684900864/Three-Benefits-of-COINmargined-Perpetual-Futures-That-You-Need-To-Know)

In general - for new people this is *no* go - you can lose all your money in a matter of minutes (this is *not* financial advice)

This isn't "trading crypto" anymore(which binance calls "spot" - like "trading on the spot"), it's a completely separate product that has its own API that differs in many ways from "Spot API":  [Coin-Margined Futures Contracts API](https://binance-docs.github.io/apidocs/delivery/en)

As it's a new API - I believe that the `binance` module doesn't support it and this would be the biggest hurdle to start trading - I would be happy to draft the initial PR(inside the `binance` module's repo) that will bring Coin-M support to *very* limited number of calls and somebody could pick it up from there as I won't use it in the immediate future - or you could do the whole PR yourself?

From the perspective of *this* course (and the book), I believe that Coin-M is not bringing anything new to the table(from the architectural/Elixir/OTP point of view). The strategy would change dramatically but the point of the course is not the strategy but Elixir/OTP.

I hope that's an acceptable answer :wink: 

Thanks,

Kamil

**Comment by MBillar** [comment]
Holly uck, surprisingly detailed answer.
Write to my telegram: __censored__
I can share all the chips and secrets in the name of your work, if there is a desire to refine

**Comment by Cinderella-Man** [comment]
As per my previous response,  support for Coin-M would be a nice feature for advanced algos/high-risk algos but it wouldn't bring any new technical challenges so it's not a good fit for the course. I will probably investigate the topic *after* finishing the series as an addon for people that are interested in trading instead of Elixir. Thank you once again for your suggestion :+1:
