### ISSUE TITLE
Handshake failure during database seed run

### ISSUE THREAD

**Issue by gugl** [frathon/hedgehog#5]
Just in case someone else experiences that error while trying to run the seed scripts:

```
TLS :client: In state :wait_cert_cr at ssl_handshake.erl:1889 generated CLIENT ALERT: Fatal - Handshake Failure
 - {:bad_cert, :hostname_check_failed}
** (MatchError) no match of right hand side value: {:error, {:http_error, %HTTPoison.Error{id: nil, reason: {:tls_alert, {:handshake_failure, 'TLS client: In state wait_cert_cr at ssl_handshake.erl:1889 generated CLIENT ALERT: Fatal - Handshake Failure\n {bad_cert,hostname_check_failed}'}}}}}
    priv/seed_settings.exs:11: (file)
    (elixir 1.11.1) lib/code.ex:931: Code.require_file/2
    (mix 1.11.1) lib/mix/tasks/run.ex:146: Mix.Tasks.Run.run/5
    (mix 1.11.1) lib/mix/tasks/run.ex:86: Mix.Tasks.Run.run/1
```

Solved it by updating the `binance`, `websockex`, `postgrex`, `jason` and `ecto_sql` dependencies.
Can't confirm which one was causing the issue but I would guess it would be enough to update to the latest `binance` version.

**Comment by Cinderella-Man** [comment]
Hi @gugl 

Thank you very much for sharing - could you please let me know which branch are you using? This issue could be related to the `binance` module as the old version was using deprecated endpoints.

Edit/Update:
----------------

I'm sorry - please ignore my question - `binance.ex` is hardcoded to the version `0.7.1` in all the branches - thank you for pointing this out - I will update the `mix.lock` in all the branches.

**Comment by Cinderella-Man** [comment]
I'm closing this one as I updated the dependencies on all the branches(which fixes this issue). Thank you very much once again for raising this and making the project better :heart:
